### ISSUE TITLE
SockJS protocol compliance?

### ISSUE THREAD

**Issue by 23doors** [flaviogrossi/sockjs-cyclone#1]
Could you provide in readme some information if it compatible with sockjs-protocol 0.1, 0.2 or 0.3?
Also, how is sockjs-protocol.py test going with it?

I know there is  a test server already and one can check it by himself by I am at research phase atm and such info would be a time saver not only for me but most likely for many.

**Comment by 23doors** [comment]
Separate issue but adding this project to PyPI would be useful!

**Comment by flaviogrossi** [comment]
the version implemented is the latest (0.3) and the server passes all the test but the websocket-related ones.

however i'm pretty confident that's not related to sockjs-cyclone itself, since i cannot seem to make the ws4py client reliably work with a pure cyclone webserver.
Also, all of the demos (and the project i'm working on which uses sockjs-cylone) works successfully using the websocket transport.

May i ask you what kind of project are you planning to implement? Also, please let me know if you ever decide to use sockjs-cyclone or if you find any issues.

As for PyPI, i plan to advertise this project more as soon as i can make all of the tests to pass.

bye

**Comment by 23doors** [comment]
Thanks for the info.

Project I am working on is a notification server for TV purposes. It's just one of many modules used to provide constant updates of subscribed information through websocket, rss and raw tcp. 

I am most likely switching from tornado + tornado-sockjs to cyclone + sockjs-cyclone or sockjs-twisted. 

Reason for switch is that redis for tornado has 2 very lousy libraries, while cyclone has great redis implementation already included. There are also some other great libraries available for cyclone/twisted while not available for tornado (or unmaintained). It seems that writing own solution for redis and others would be more work than changing framework from tornado to cyclone. Also, latest benchmarks shows that cyclone/twisted has finally become in par with tornado's speed.

Anyway, sockjs for tornado is great and I am looking for an alternative. If your library is working with major browsers, this is the one I will use.

It would be great if you could add your project to PyPI more sooner than later :) It's much easier to maintain requirements with it than maintaining manual install from source.

**Comment by flaviogrossi** [comment]
just uploaded sockjs-cyclone to pypi. Hope it will work ok for you.

As a side note (and just FYI if you happen not to know this feature), for projects not on pypi or for which i need to quickly follow changes, i use to fetch the sources with pip directly from github. The syntax is:

```
pip install git+git://github.com/flaviogrossi/sockjs-cyclone.git
```

**Comment by 23doors** [comment]
Thanks, I will check it out!

About pip installing from git sources. I know about this method but I find it difficult to maintain. To check for updates I have to check the repo. Updating is also a pain as it is different than all other modules. It's also much easier to change versions for comparison or when new issues appear (checking past versions without the need to find the commit for it).

As a general rule, I try to use only pypi packages because of all this, whenever possible. So thanks for making my life easier ;)
